### ISSUE TITLE
Permissions being forgotten upon relogging

### ISSUE THREAD

**Issue by blondetheftauto** [atesin/PermissionShell#1]
Hello! 

I'm having an issue where my player's permissions are being forgotten upon relog. Is there a way to fix this?

Thank you!

**Comment by atesin** [comment]
hi, thanks for your interest

permissionshell is more intended for testing permissions in plugin development, it seems that permission attachments are stored in memory though, maybe that's because it resets (against server registered permissions), you should't rely this plugin for manage permissions in a production server

for that better use some other **persistent** permission plugin like permissionsex, bpermissions or bukkitpermissions
